### ISSUE TITLE
An exception is thrown when using any decoration feature if using file scoped namespaces

### ISSUE THREAD

**Issue by AlexBagnolini** [d1820/proto-attributor#7]
When trying to decorate a file that uses file scoped namespaces, for example:

```C#
namespace MuSuperNamespace;

public class ClientStatus
{
    public int UserId { get; set; }
}
```

Shows a messagebox reporting: `Object reference not set to an instance of an object.`

**Comment by d1820** [comment]
Issue has been resolved with version 1.1 not available in the VS Marketplace
